import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const source = readFileSync(
  resolve(process.cwd(), 'scripts/verify-app-runtime-live-e2e.ts'),
  'utf8'
)

assert.match(source, /APP_RUNTIME_E2E_REDIS_ISOLATED/)
assert.match(source, /APP_RUNTIME_E2E_REDIS_DB/)
assert.match(source, /redis\.call\('DBSIZE'\)/)
assert.match(source, /redis\.call\('SET'/)
assert.match(source, /redis\.call\('GET'/)
assert.match(source, /redis\.call\('FLUSHDB'\)/)
assert.match(source, /for \(const value of \[\s*ownerUsername,\s*ownerEmail,\s*ownerPhone,/)
assert.match(source, /process\.on\('SIGINT'/)
assert.match(source, /process\.on\('SIGTERM'/)
assert.match(source, /await waitForForcedExit/)
assert.doesNotMatch(source, /Redis cleanup warning|Database cleanup warning/)
assert.match(source, /if \(terminationController\.signal\.aborted\) throw/)
assert.match(source, /if \(backendStopped\) \{/)
assert.match(source, /Failure evidence collection failed/)
assert.doesNotMatch(source, /await page\.reload\(/)
assert.match(source, /getByRole\('button', \{ name: 'Reload' \}\)/)
assert.match(source, /__agentStudioMessageListenerCount/)
assert.match(source, /reloaded iframe body/)
assert.match(source, /reloaded host page/)
assert.match(source, /reloaded browser console/)
assert.match(source, /APP_RUNTIME_CAPABILITIES_ENABLED/)
assert.match(source, /APP_RUNTIME_CAPABILITY_RATE_LIMIT_PER_MINUTE/)
assert.match(source, /approved_capabilities: \['context\.read'\]/)
assert.match(source, /capabilities: \['context\.read'\]/)
assert.match(source, /app_runtime_session/)
assert.match(source, /token_hash/)
assert.match(source, /cross-tenant runtime token denial/)
assert.match(source, /expired runtime token denial/)
assert.match(source, /revoked runtime token denial/)
assert.match(source, /uninstall runtime invalidation/)
assert.match(source, /runtime capability rate limiting/)
assert.match(source, /retry_after/)
assert.match(source, /app_runtime_audit_log/)
assert.doesNotMatch(source, /console\.log\([^\n]*(?:session\.token|runtimeToken)/)

assert.match(source, /APP_RUNTIME_E2E_HTTP_URL/)
assert.match(source, /APP_RUNTIME_E2E_WEBHOOK_URL/)
assert.match(source, /APP_RUNTIME_E2E_REDIRECT_PRIVATE_URL/)
assert.match(source, /APP_RUNTIME_STORAGE_DIR/)
assert.match(source, /APP_RUNTIME_IFRAME_LAUNCH_ENABLED/)
assert.match(source, /APP_RUNTIME_LAUNCH_SECRET/)
assert.match(source, /runtime-e2e\.invalid/)
assert.match(source, /context\.route\(iframeFixturePattern/)
assert.match(source, /verify iframe exact-origin handshake/)
assert.match(source, /verify iframe launch replay denial/)
assert.match(source, /verify iframe origin denial/)
assert.match(source, /verify runtime KV lifecycle/)
assert.match(source, /verify runtime file lifecycle/)
assert.match(source, /verify runtime HTTP lifecycle/)
assert.match(source, /verify runtime webhook lifecycle/)
assert.match(source, /verify cross-tenant KV denial/)
assert.match(source, /verify cross-tenant file denial/)
assert.match(source, /verify private-address denial/)
assert.match(source, /verify redirected private-address denial/)
assert.match(source, /verify capability revocation/)
assert.match(source, /app_runtime_kv/)
assert.match(source, /app_storage_object/)
assert.match(source, /app-runtime:iframe-launch:/)
assert.match(source, /assertDatabaseRemoved/)
assert.match(source, /assertArtifactCleanup/)
assert.match(source, /assertNoSensitiveValue\('redacted diagnostics'/)
assert.doesNotMatch(source, /NODE_TLS_REJECT_UNAUTHORIZED/)
assert.doesNotMatch(
  source,
  /APP_RUNTIME_E2E_(?:DB_PASSWORD|PLATFORM_PASSWORD|REDIS_PASSWORD)\s*[:=]\s*['"][^'"]+['"]/
)

console.log('App runtime live E2E contract verified.')
